app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:  /admin/

hello:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admineasy

exams:
    type: rest
    resource: AppBundle\Controller\APIController
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

